apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-liftshift
  labels:
    app: liftshift
    type: cost-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-liftshift
  template:
    metadata:
      labels:
        app: flask-liftshift
    spec:
      containers:
      - name: flask-app
        image: tiangolo/uwsgi-nginx-flask:python3.8
        ports:
        - containerPort: 80
